---
title: "Model Specifications"
subtitle: "EC 320: Introduction to Econometrics"
author: "Philip Economides"
date: "Winter 2022"
output:
  xaringan::moon_reader:
    css: ['default', 'metropolis', 'metropolis-fonts', 'my-css.css']
    # self_contained: true
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
class: inverse, middle

```{r Setup, include = F}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(echo = TRUE, cache=TRUE)

library(pacman)
p_load(ggthemes, viridis, knitr, AER, extrafont, tidyverse, magrittr, wooldridge, stargazer, latex2exp, parallel, broom, kableExtra, ggforce, margins, furrr, gapminder)
# Define colors
red_pink <- "#e64173"
turquoise <- "#20B2AA"
orange <- "#FFA500"
red <- "#fb6107"
blue <- "#2b59c3"
green <- "#8bb174"
grey_light <- "grey70"
grey_mid <- "grey50"
grey_dark <- "grey20"
purple <- "#6A5ACD"
met_slate <- "#23373b" # metropolis font color
# Knitr options
opts_chunk$set(
  comment = "#>",
  fig.align = "center",
  fig.height = 7,
  fig.width = 10.5,
  #dpi = 300,
  #cache = T,
  warning = F,
  message = F
)  
theme_simple <- theme_bw() + theme(
  axis.line = element_line(color = met_slate),
  panel.grid = element_blank(),
  rect = element_blank(),
  strip.text = element_blank(),
  text = element_text(family = "Fira Sans", color = met_slate, size = 14),
  axis.text.x = element_text(size = 12),
  axis.text.y = element_text(size = 12),
  axis.ticks = element_blank(),
  plot.title = element_blank(),
  legend.position = "none"
)
theme_empty <- theme_bw() + theme(
  line = element_blank(),
  rect = element_blank(),
  strip.text = element_blank(),
  axis.text = element_blank(),
  plot.title = element_blank(),
  axis.title = element_blank(),
  plot.margin = structure(c(0, 0, -1, -1), unit = "lines", valid.unit = 3L, class = "unit"),
  legend.position = "none"
)
theme_axes <- theme_empty + theme(
  axis.title = element_text(size = 18),
  text = element_text(family = "Fira Sans", color = met_slate, size = 14),
  plot.margin = structure(c(0, 0, 0.1, 0), unit = "lines", valid.unit = 3L, class = "unit")
)
# Returns education data
wage2 <- get('wage2')
# MI school funding and test scores data
meap01 <- get('meap01') %>% 
  mutate(exppp = exppp/1000)
```

# Prologue

---
# Housekeeping

<br>

.hi-pink[Data Projects] are in!

- I will have those graded by the weekend

- Points based on the quality of submissions and presentation of results

--

.hi-pink[Problem Set 5]

- Due Monday, March 7th

---

# Model Specification

Concerns the following questions of a given model:

--

What are the consequences of including in the regression model a variable that should not be there?

--

.hi-pink[Multicollinearity]


--

What are the consequences of excluding a variable that should be featured?

--

.hi-pink[Omitted Variable Bias]
 
--
 
How do we test restrictions to model specifications?

--

.hi-pink[t and F tests]

---

# Model Specification

<br>
 
What happens if you have difficulty finding data on a variable and use a proxy instead?


.hi-pink[Today's lesson]

--

We will then go a useful approach to know for policy analysis: the .hi-pink[difference-in-difference] model


---
class: inverse, middle

# Proxies in Model Specifications

---
# Proxies

<br>

Suppose you are considering the following model
$$
\begin{aligned}
Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + u
\end{aligned}
$$

While $X_1$ is observed, lets consider a case where $X_2$ is an unobserved variable. Cases of unobservable data could include:

- Vaguely defined with no explicit measure (e.g. quality of education)
- Intangible and cannot be quantified (e.g. utility, ability)
- Requires so much time/energy that measurement is infeasible
- Confidentiality, privacy concerns may limit observed data availability

---

# Proxies

<br>

Rather than exclude the unobservable, you may wish to use an adequate .hi-pink[proxy] variable for $X_2$.

A .hi-pink[proxy] variable is a substitute variable that may reasonably be supposed to maintain similar properties to our missing variable. 

.hi-blue[Example:] For quality of education, we could use the student-staff ratio to have a measure of how many resources the educational institution makes available to students. Where quality is high, student-staff ratios are low. 
 
---

# Proxies

<br>

Returning to the model, our true data generating process for Y:
$$
\begin{aligned}
Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + u
\end{aligned}
$$
In the case where we have no data on $X_2$, suppose we have an .hi-blue[ideal proxy] for it such that there exists an *exact linear relationship $X_2$ and $Z$*:
$$
\begin{aligned}
X_2 = \lambda + \mu Z,
\end{aligned}
$$

where $\lambda$ and $\mu$ are fixed, unknown constants. We cannot estimate them by running a regression of the above relationship, since we have no data on $X_2$. .hi-pink[Let's sub in our expression and see what using Z achieves].

---

# Inference using Proxies

Using $X_2 = \lambda + \mu Z$,
$$
\begin{aligned}
Y = & \beta_0 + \beta_1 X_1 + \beta_2 X_2 + u\\
  = & \beta_0 + \beta_1 X_1 + \beta_2 (\lambda + \mu Z) + u\\
  = & (\beta_0 + \beta_2 \lambda) + \beta_1 X_1 + \beta_2 \mu Z + u\\
  = & \ \ \ \ \ \  \ \alpha \ \ \ \ \ \ \ \ \ + \beta_1 X_1 + \ \ \gamma_2 Z + u
\end{aligned}
$$


Takeaways:

1. $\beta_1$, its standard error and t-stat will be same as if $X_2$ used
1. $R^2$ will be the same as if $X_2$ was used instead of Z
1. The coefficient of Z, $\gamma_2$, will be estimate of $\beta_2 \mu$, and not possible to estimate $\beta_2$ directly
1. t-stat for $\gamma_1$ same as $\beta_2$, so able to assess significance of $X_2$
1. Not possible to estimate $\beta_0$ since we now only see $\alpha$


---

# Risks of using Proxies

Validity of all the subsequent takeaways rely on the condition that $Z$ is an ideal proxy for $X_2$

- In practice, unusual to find a proxy that is exactly linearly related to our missing variable

- If the relationship is close to linear, the results will hold **approximately**

-  The biggest problem faced is that there is never any manner by which to test this condition of whether the approximated difference is sufficiently small

- Critical thinking in explaining your logical link between $X_2$ & $Z$ and accepting that you are relying on a strong assumptions are often required to convince an audience that a proxy is indeed valid 

---
class: inverse, middle

# Difference-in-Difference (DiD)

---

# DiD: Concept



---


# DiD: Structure



---

# DiD: Examples



---

# DiD: Interpretation



---

# DiD: Required Assumption



